name: Multi-platform build test
on: push
env:
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Run vcpkg
        run: ${{ github.workspace }}/vcpkg/vcpkg install

      - name: Initialize
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cmake --build build

  windows-build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Initialize
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Build
        run: |
          cmake --build build --config Release

  macos-intel-build:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Initialize
        run: |
            mkdir build
            cd build
            cmake ..

      - name: Build
        run: |
            cmake --build build --config Release

  macos-arm-build:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Initialize
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Build
        run: |
          cmake --build build --config Release