name: Multi-platform build test
on: push

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install required packages
        run: |
          apt install libgtk-4-dev -y

      - name: Initialize
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cmake --build build

  windows-build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Initialize
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Build
        run: |
          cmake --build build --config Release

  macos-intel-build:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Initialize
        run: |
            mkdir build
            cd build
            cmake ..

      - name: Build
        run: |
            cmake --build build --config Release

  macos-arm-build:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Initialize
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Build
        run: |
          cmake --build build --config Release
